apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-demo
  template:
    metadata:
      labels:
        app: hello-demo
        track: stable
    spec:
      containers:
        - name: hello-demo
          image: 10.3.10.131:5000/hello-demo:v${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-demo-svc
spec:
  type: NodePort
  selector:
    app: hello-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080